Add command line argument to specify target
sandersn/downlevel-dts pull request #44
Opened 2020-10-18 06:57 UTC by L2jLiga

issue #36 

*Usage*:
```
npx downlevel-dts . ts3.8 --to=3.8
```

2020-10-26 16:02 UTC, sandersn requested changes
Need to use the semver package instead of number parsing.

2020-10-26 21:32 UTC, L2jLiga commented on baselines/ts4/test.d.ts
> +/// <reference path="./src/test.d.ts" />
Right

2020-10-27 06:41 UTC, L2jLiga commented on index.js
> +    const targetVersionArg = parseFloat(to.split("=")[1]);
Sure, I updated PR and now it uses semver

2020-10-27 14:53 UTC, sandersn approved these changes

2020-10-27 14:53 UTC, merged

2020-10-27 15:59 UTC, sandersn commented
Having the test output in the `test` folder was causing multiple test runs to read output as input, so I moved to the baselines/local and baselines/reference structure that TS itself uses.